---
jobs:
  build:
    name: 'Perl ${{ matrix.perl }}'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v3
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '${{ matrix.perl }}'
      - name: Install dependencies
        run: cpanm -nq --installdeps --with-develop --with-recommends .
      - name: Run test
        run: prove -lr t
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        perl:
          - 5.36
          - 5.38
name: CI
on:
  workflow_call:
    inputs:
      flags:
        required: true
        type: string
      os:
        required: true
        type: string
      perl:
        required: true
        type: string
