---
abstract: "I'm afraid it's terminal..."
author:
  - 'Sanko Robinson <30663+sanko@users.noreply.github.com>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.034'
  perl: v5.40.0
dynamic_config: 1
generated_by: 'App::mii v1.0.0, CPAN::Meta::Converter version 2.150013'
keywords: []
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Cancer
no_index:
  directory: []
  file: []
  namespace: []
  package: []
provides:
  Cancer:
    file: lib/Cancer.pm
    version: v0.0.1
  Cancer::Ansi:
    file: lib/Cancer/Ansi.pm
    version: v0.0.1
  Cancer::Ansi::Iterm2:
    file: lib/Cancer/Ansi/Iterm2.pm
    version: v0.0.1
  Cancer::Ansi::Kitty:
    file: lib/Cancer/Ansi/Kitty.pm
    version: v0.0.1
  Cancer::Ansi::Kitty::Decoder:
    file: lib/Cancer/Ansi/Kitty/Decoder.pm
    version: v0.0.1
  Cancer::Ansi::Kitty::Encoder:
    file: lib/Cancer/Ansi/Kitty/Encoder.pm
    version: v0.0.1
  Cancer::Ansi::Parser:
    file: lib/Cancer/Ansi/Parser.pm
  Cancer::Ansi::Sixel:
    file: lib/Cancer/Ansi/Sixel.pm
    version: v0.0.1
  Cancer::Ansi::Sixel::Raster:
    file: lib/Cancer/Ansi/Sixel.pm
    version: v0.0.1
  Cancer::Ansi::Sixel::Repeat:
    file: lib/Cancer/Ansi/Sixel.pm
    version: v0.0.1
  Cancer::Ansi::Style:
    file: lib/Cancer/Ansi.pm
  Cancer::Bubbles:
    file: lib/Cancer.pm
  Cancer::Lipgloss:
    file: lib/Cancer.pm
  Cancer::Term:
    file: lib/Cancer/Term.pm
    version: v0.0.1
  Cancer::Term::File:
    file: lib/Cancer/Term/File.pm
    version: v0.0.1
  Cancer::Term::State:
    file: lib/Cancer/Term/State.pm
    version: v0.0.1
  Cancer::Term::Unix:
    file: lib/Cancer/Term/Unix.pm
    version: v0.0.1
  Cancer::Term::Windows:
    file: lib/Cancer/Term/Windows.pm
    version: v0.0.1
  Cancer::Util:
    file: lib/Cancer/Util.pm
    version: v0.0.1
recommends:
  Term::ReadKey: '0'
requires:
  Acme::Parataxis: '0'
  Affix: '0'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: v0.0.1
x_custom_builder: 0
x_ignore:
  - .tidyallrc
  - .gitignore
  - .clang-format
  - .github/**
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
