requires 'perl', '5.036000';

# TODO: remove this!!!!
requires 'Data::Dump';
#
on 'test' => sub {
    requires 'Test2::V0';
    requires 'Test2::Tools::Compare';
    requires 'Test2::Plugin::UTF8';
    requires 'Data::Dumper';
    requires 'Math::BigInt';
    requires 'Devel::CheckBin';
};
on 'configure' => sub {
    requires 'Module::Build::Tiny';
};
on 'develop' => sub {
    requires 'CPAN::Uploader';
    requires 'Code::TidyAll';
    requires 'Code::TidyAll::Plugin::ClangFormat';
    requires 'Code::TidyAll::Plugin::PodTidy';
    requires 'Code::TidyAll::Plugin::YAML';
    requires 'Perl::Tidy';
    requires 'Pod::Tidy';
    requires 'Test::CPAN::Meta';
    requires 'Test::MinimumVersion::Fast';
    requires 'Test::PAUSE::Permissions';
    requires 'Test::Pod' => 1.41;
    requires 'Test::Spellunker';
    requires 'Version::Next';
    requires 'Pod::Markdown::Github';
    requires 'Software::License::Artistic_2_0';
    requires 'Minilla';
};
