name: MacOS

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
    schedule:
        - cron: '42 5 * * 0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
        perl:
          - 5.38
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpanm --installdeps -v -n .
      - name: Install dependencies
        run: cpanm --notest --quiet --installdeps --with-develop --with-recommends .
      - uses: Yuri6037/Action-FakeTTY@1abc69c7d530815855caedcd73842bae5687c1a6
        if: ${{ matrix.os != 'windows-latest' }}
      - name: Run tests
        # https://github.com/actions/runner/issues/241
        run: ${{ matrix.os != 'windows-latest' && 'faketty '|| '' }}prove -lv t
